# Generated by Django 3.0.8 on 2020-07-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(db_index=True, upload_to='banners/banner_upper', verbose_name='Изображение баннера')),
                ('link', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Ссылка на акцию/товар')),
                ('publish', models.BooleanField(default=False, verbose_name='Опубликован на главной')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='Banner3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(db_index=True, upload_to='banners/3_in_block')),
                ('link', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Ссылка на акцию/товар')),
                ('publish', models.BooleanField(default=False, verbose_name='Опубликован на главной')),
            ],
            options={
                'verbose_name': 'Баннер (блок по 3)',
                'verbose_name_plural': 'Баннеры (блок по 3)',
            },
        ),
        migrations.CreateModel(
            name='BannerL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(db_index=True, upload_to='banners/banner_large', verbose_name='Изображение банера')),
                ('link', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Ссылка на акцию/товар')),
                ('publish', models.BooleanField(default=False, verbose_name='Опубликован на главной')),
            ],
            options={
                'verbose_name': 'Баннер (длинный)',
                'verbose_name_plural': 'Баннер (длинный)',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, verbose_name='Название бренда')),
                ('name_slug', models.SlugField(unique=True)),
                ('image', models.ImageField(db_index=True, upload_to='brands_logo', verbose_name='Изображение логотипа')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='CatBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(db_index=True, upload_to='banners/category_banners', verbose_name='Изображение')),
                ('link', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Ссылка')),
                ('publish', models.BooleanField(default=False, verbose_name='Опубликован в категориях')),
            ],
            options={
                'verbose_name': 'Баннер в категориях',
                'verbose_name_plural': 'Баннеры в категриях',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название организации')),
                ('image', models.ImageField(blank=True, db_index=True, upload_to='logo', verbose_name='Логотип')),
                ('desc', models.TextField(blank=True, verbose_name='Описание организации')),
                ('adress', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Адрес')),
                ('mail', models.EmailField(blank=True, db_index=True, max_length=50, verbose_name='Эл. почта')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Телефон')),
                ('webphone', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Whatsapp')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50, verbose_name='Ваше Имя')),
                ('mail', models.EmailField(db_index=True, max_length=50, verbose_name='Ваша почта')),
                ('company', models.CharField(blank=True, db_index=True, max_length=1501, verbose_name='Организация')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=18, verbose_name='Телефон')),
                ('message', models.TextField(max_length=300, verbose_name='Сообщение')),
                ('agreement', models.BooleanField(db_index=True, default=True, verbose_name='Согласие на передачу персональных данных')),
            ],
            options={
                'verbose_name': 'Контактная форма',
                'verbose_name_plural': 'Контактные формы',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название страницы')),
                ('name_slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, db_index=True, upload_to='pages', verbose_name='Изображение')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=1500, verbose_name='Текст страницы')),
                ('publish', models.BooleanField(default=True, verbose_name='Опубликованно')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('title_1', models.CharField(db_index=True, max_length=50, verbose_name='Заголовок 1')),
                ('title_2', models.CharField(db_index=True, max_length=50, verbose_name='Заголовок 2')),
                ('desc', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Описание слайда')),
                ('image', models.ImageField(db_index=True, upload_to='slider', verbose_name='Изображение слайда')),
                ('link', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Ссылка к слайду')),
                ('order', models.BooleanField(default=True, verbose_name='Включить заказ?')),
                ('good_link', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Ссылка на товар для заказа')),
                ('publish', models.BooleanField(default=True, verbose_name='Вкл/Выкл показ на главной')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(db_index=True, max_length=50, verbose_name='Электронная почта')),
                ('agreement', models.BooleanField(db_index=True, default=True, verbose_name='Согласие на передачу персональных данных')),
            ],
            options={
                'verbose_name': 'Электронная почта',
                'verbose_name_plural': 'Список Email-ов',
            },
        ),
    ]
